### ISSUE TITLE
Vector of string is not handled correctly 

### ISSUE THREAD

**Issue by EttoreVidotto** [ADLINK-IST/idlpp-cxx#10]
Hello everyone,
I am having troubles working with a vector of strings. I have the following IDL file:

``` c++
module Msg
{
struct StringSeq {
	long id;
	sequence<string<10>, 5> names;
};
#pragma keylist StringSeq id
};
```
which should allow me to work with a vector with at most 5 strings of maximal 10 characters.
Now, I would like to write a message using cyclonedds-cxx. To this end, I just took the helloworld example, I changed the IDL file with mine above and replaced the content of the file publisher.cpp with:
``` c++
#include <iostream>
#include "dds/dds.hpp"
#include "StringSeq_DCPS.hpp"
using namespace org::eclipse::cyclonedds;
int main() {
    dds::domain::DomainParticipant participant(domain::default_id());
    dds::topic::Topic<Msg::StringSeq> topic(participant, "StringSeq");
    dds::pub::Publisher publisher(participant);
    dds::pub::DataWriter<Msg::StringSeq> writer(publisher, topic);
    std::vector<std::string> stringVector{"Name1", "Name2", "Name3"};
    Msg::StringSeq msg(18, stringVector);
    writer.write(msg);
    std::cout << "Messagge written." << std::endl;
    return EXIT_SUCCESS;
}
```
However, the execution results in an error when the function __Msg_StringSeq__copyIn in the file StringSeqSplDcps.cpp tries to "strncpy" the first entry of stringVector in an invalid location, since the components of dest0 have not been initialized properly in the previous line of code:
``` c++
dest0 = (length0 == 0) ? 0 : (char * *)dds_alloc(length0 * sizeof(char *));
```
Is this problem caused because a corresponding for-loop is missing in the function idl_seqAllocBuffer in the file idl_genLiteISOCxxCopyin.c?

Thank you in advance, any help would be appreciated.
Best regards,
Ettore Vidotto

**Comment by ThijsSassen** [comment]
hi @EttoreVidotto can you check if this works with our new idl compiler which can be found here: https://github.com/eclipse-cyclonedds/cyclonedds-cxx/tree/idlcxx

**Comment by EttoreVidotto** [comment]
Hi @ThijsSassen Thank you very much for your answer. Yes, this works with the new idl compiler.
