### ISSUE TITLE
[Bug] Linker Error on Clang 13 Compiler

### ISSUE THREAD

**Issue by dkroenke** [ADLINK-IST/idlpp-cxx#11]
Hi,
while compiling idlpp-cxx with the latest clang stable release i encountered the following linker errors:
```bash
/usr/bin/ld: CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/set.c.o:(.bss+0xc): multiple definition of `expr_sharp'; CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/eval.c.o:(.bss+0xc): first defined here
/usr/bin/ld: CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/sharp.c.o:(.bss+0x0): multiple definition of `ifstack'; CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/at.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/sharp.c.o:(.bss+0x8): multiple definition of `n_skipped_ifs'; CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/at.c.o:(.bss+0x8): first defined here
/usr/bin/ld: CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/undef.c.o:(.bss+0x0): multiple definition of `ifstack'; CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/at.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/undef.c.o:(.bss+0x8): multiple definition of `n_skipped_ifs'; CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/at.c.o:(.bss+0x8): first defined here
/usr/bin/ld: CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/while.c.o:(.bss+0x0): multiple definition of `ifstack'; CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/at.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/while.c.o:(.bss+0x8): multiple definition of `n_skipped_ifs'; CMakeFiles/cppgen.dir/__/ppresources/ospli/src/cpp/code/at.c.o:(.bss+0x8): first defined here
```
Happens on idlpp-cxx-1.0.0 and master branch. With clang-10 everything compiles. I guess this happens due some global declarations in header files.

Affected global declarations in the following files:
idlpp/ppresources/ospli/src/cpp/code/expr.h - ```int expr_sharp;```
idlpp/ppresources/ospli/src/cpp/code/if.h - ```IF *ifstack;```
idlpp/ppresources/ospli/src/cpp/code/if.h - ```int n_skipped_ifs;```
idlpp/ppresources/ospli/src/tools/idlpp/code/idl_genIdlHelper.h - ```os_iter idl_idlScopeKeyList;```
idlpp/ppresources/ospli/src/tools/idlpp/code/idl_genIdlHelper.h - ```os_iter idl_idlScopeStreamsList;```

I guess these variables need to be declared, but i'm not sure about the implications in the overall system.

**Comment by ThijsSassen** [comment]
@dkroenke thanks for letting us know. Can you try it with our new idl compiler which can be found here: https://github.com/eclipse-cyclonedds/cyclonedds-cxx/tree/idlcxx

**Comment by bitpet** [comment]
try passing `-fcommon` flag to the compiler

**Comment by dkroenke** [comment]
It works fine with the new idl compiler, will close this here.
